subroutine reset_metropolis_acceptance_counters
use variables
implicit none

no_of_accepted_field_rotations_per_site = 0.0d0
no_of_accepted_charge_hops_per_site = 0.0d0
no_of_accepted_external_global_moves = 0.0d0

end subroutine reset_metropolis_acceptance_counters
